// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"cert/internal/controller"
	"cert/internal/controller/health"
	"github.com/google/wire"
)

// Injectors from wire.go:

func ProvideHealthController() (health.HealthController, error) {
	healthController := health.NewHealthController()
	return healthController, nil
}

func ProvideUrlMappings() controller.UrlMapping {
	healthController := health.NewHealthController()
	urlMapping := controller.NewUrlMapping(healthController)
	return urlMapping
}

// wire.go:

var healthControllerSet = wire.NewSet(health.NewHealthController)

var controllerSet = wire.NewSet(
	healthControllerSet, controller.NewUrlMapping,
)
